# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0005_auto_20170522_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(null=True),
        ),
    ]
